language: go
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install zlib1g-dev -qq
install:
  - curl -4L http://fallabs.com/kyotocabinet/pkg/kyotocabinet-1.2.76.tar.gz
  - cd /tmp && tar -xzf kyotocabinet-1.2.76.tar.gz
  - cd /tmp/ && ./configure && make && sudo make install
script: cd kc && go test
